# ArgoCD NodePort Service
# This creates an additional NodePort service for direct ArgoCD access
# without going through ingress sub-path routing.
#
# ArgoCD is installed with server.insecure=true, so it runs on HTTP port 8080
#
# Access:
# - Staging: http://staging-goapps.mutugading.com:30080
# - Production: http://goapps.mutugading.com:30080
#
apiVersion: v1
kind: Service
metadata:
  name: argocd-server-nodeport
  namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080  # ArgoCD server HTTP port (insecure mode)
      nodePort: 30080   # Fixed NodePort for consistent access
      protocol: TCP
  selector:
    app.kubernetes.io/name: argocd-server
