# MinIO environment patch for Staging
# Sets the correct environment variables for direct port access (not subpath)
# 
# Required variables:
# - MINIO_BROWSER_REDIRECT_URL: Full URL for browser redirects (with port)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
spec:
  template:
    spec:
      containers:
        - name: minio
          env:
            - name: MINIO_BROWSER_REDIRECT_URL
              value: "https://staging-goapps.mutugading.com:30090/"
