apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: goapps-production
resources:
- ../../base
patches:
- path: patches/resources.yaml
- path: patches/env-iam-storage.yaml
images:
- name: ghcr.io/mutugading/finance-service
  newTag: dfbcd52
