apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: goapps-staging
resources:
- ../../base
patches:
- path: patches/resources.yaml
images:
- name: ghcr.io/mutugading/finance-cost-orchestrator
  newTag: 9eeef74
