# MinIO environment patch for Staging
# Sets the correct MINIO_BROWSER_REDIRECT_URL for sub-path routing
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
spec:
  template:
    spec:
      containers:
        - name: minio
          env:
            - name: MINIO_BROWSER_REDIRECT_URL
              value: "https://staging-goapps.mutugading.com/minio/"
