apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Production Environment Overlay
# Backup path: /goapps-backup

namespace: database

resources:
  - ../../base/backup/cronjobs

patches:
  # Patch backup path for production VPS
  - target:
      kind: CronJob
      name: postgres-backup-morning
    patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/env/0/value
        value: "production"
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/volumes/0/hostPath/path
        value: "/goapps-backup/postgres"

  - target:
      kind: CronJob
      name: postgres-backup-afternoon
    patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/env/0/value
        value: "production"
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/volumes/0/hostPath/path
        value: "/goapps-backup/postgres"

  - target:
      kind: CronJob
      name: postgres-backup-night
    patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/env/0/value
        value: "production"
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/volumes/0/hostPath/path
        value: "/goapps-backup/postgres"
