# PgBouncer VPA - Vertical Pod Autoscaler
# Mode: Off - recommendations only, no auto-restart
# Reason: PgBouncer should have high availability, avoid unexpected restarts
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: pgbouncer-vpa
  namespace: database
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pgbouncer
  updatePolicy:
    updateMode: "Off"  # Recommendations only, apply manually
  resourcePolicy:
    containerPolicies:
      - containerName: pgbouncer
        minAllowed:
          cpu: "25m"
          memory: "32Mi"
        maxAllowed:
          cpu: "500m"
          memory: "256Mi"
        controlledResources: ["cpu", "memory"]
