apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: goapps-production
resources:
- ../../base
patches:
- path: patches/resources.yaml
- path: patches/hpa.yaml
- path: patches/env-finance.yaml
images:
- name: ghcr.io/mutugading/finance-cost-worker
  newTag: 8df1bc8
