# ArgoCD Application - Infrastructure Backup (Staging)
# Uses staging overlay with /staging-goapps-backup paths
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-backup
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: goapps
  source:
    repoURL: https://github.com/mutugading/goapps-infra.git
    targetRevision: main
    path: overlays/staging/backup
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
