# MinIO environment patch for Production
# Sets the correct environment variables for sub-path routing
# 
# Required variables:
# - MINIO_BROWSER_REDIRECT_URL: Full URL for browser redirects
# - MINIO_CONSOLE_SUBPATH: The sub-path where console is served
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
spec:
  template:
    spec:
      containers:
        - name: minio
          env:
            - name: MINIO_BROWSER_REDIRECT_URL
              value: "https://goapps.mutugading.com/minio/"
            - name: MINIO_CONSOLE_SUBPATH
              value: "/minio"
